spring:
  application:
    name: springboot car service application
  datasource:
    url: "jdbc:mysql://localhost:3306/richard"
    username: "admin"
    password: "password"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      uri: mongodb+srv://admin:rootroot@cluster0.mhxvtmj.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: maintenance
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${mail-sender}
#    password: ${mail-password}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
logging:
  level:
    sun:
      rmi:
        transport:
          tcp: OFF
jwt:
  secret: RICHARD_MY_BELOVED_CAT
  access-token:
    ttl-millis: 100*60*60
  refresh-token:
    ttl-millis: 100*60*60*24